name: continuous-integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make setup-dev
      - name: Run pytest (unit tests) and bandit (security test)
        env:
          HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
        run: |
          sed '/^api_key/s/=.*$/= '$HEROKU_PASSWORD'/' config.ini
          make security-test
          make test